# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'engez.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Eng-EZ")
        MainWindow.resize(592, 369)
        MainWindow.setStyleSheet("background-color: rgb(205, 253, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 40, 281, 41))
        self.label.setMinimumSize(QtCore.QSize(161, 0))
        self.label.setStyleSheet("font: 75 14pt \"\";\n"
"font: 18pt \"Times New Roman\";")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 140, 75, 23))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 151, 21))
        self.label_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 70, 151, 51))
        self.label_3.setStyleSheet("font: 8pt \"Sitka Text\";\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(220, 100, 131, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(220, 130, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(220, 160, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(220, 190, 131, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(220, 220, 121, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 320, 461, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 290, 131, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 260, 171, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(152, 202, 225);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eng-EZ"))
        self.label.setText(_translate("MainWindow", "Select Options"))
        self.pushButton.setText(_translate("MainWindow", "Upload file"))
        self.pushButton_2.setText(_translate("MainWindow", "Download pdf"))
        self.label_2.setText(_translate("MainWindow", "Upload .txt file"))
        self.label_3.setText(_translate("MainWindow", "download pdf"))
        self.checkBox.setText(_translate("MainWindow", "max no of Definations"))
        self.checkBox_2.setText(_translate("MainWindow", "synonyms"))
        self.checkBox_3.setText(_translate("MainWindow", "examples"))
        self.checkBox_4.setText(_translate("MainWindow", "part Of Speech"))
        self.checkBox_5.setText(_translate("MainWindow", "Wikipedia Link"))
        self.label_4.setText(_translate("MainWindow", "Progress"))
        self.pushButton_3.setText(_translate("MainWindow", "Start Script"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
